### ISSUE TITLE
[BUG] Deleting all rss feeds

### ISSUE THREAD

**Issue by NoobSam777** [msasikanth/twine#464] opened 2024-04-18 00:45 UTC
**Describe the bug**
The app is deleting all rss feeds often.

**To Reproduce**
It's random

**Screenshots**
Without screenshot

**Device Information**
 - Device: Redmi note 8 with custom rom
 - OS: Android 12
 - App Version: 1.128.0-internal

**Stacktrace**
```
android.database.sqlite.SQLiteDatabaseCorruptException: database disk image is malformed (code 11)
	at io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at io.requery.android.database.sqlite.SQLiteConnection.executeForCursorWindow(Unknown Source:89)
	at io.requery.android.database.sqlite.SQLiteSession.executeForCursorWindow(Unknown Source:36)
	at io.requery.android.database.sqlite.SQLiteQuery.fillWindow(Unknown Source:30)
	at io.requery.android.database.sqlite.SQLiteCursor.fillWindow(Unknown Source:30)
	at io.requery.android.database.sqlite.SQLiteCursor.getCount(Unknown Source:6)
	at io.requery.android.database.AbstractCursor.moveToPosition(Unknown Source:0)
	at io.requery.android.database.AbstractCursor.moveToNext(Unknown Source:4)
	at p2.a.d(Unknown Source:2)
	at l2.b.a(Unknown Source:269)
	at l2.b.l(Unknown Source:28)
	at p2.c.a(Unknown Source:18)
	at s.X.l(Unknown Source:280)
	at p2.i.c(Unknown Source:29)
	at p2.i.h(Unknown Source:22)
	at i4.J.a(Unknown Source:25)
	at l2.c.b(Unknown Source:6)
	at s.p.l(Unknown Source:101)
	at l2.i.c(Unknown Source:54)
	at g2.f.s1(Unknown Source:6)
	at q2.b.y(Unknown Source:57)
	at w5.a.r(Unknown Source:8)
	at R5.O.run(Unknown Source:112)
	at m.j.run(Unknown Source:29)
	at X5.j.run(Unknown Source:2)
	at X5.a.run(Unknown Source:95)
	Suppressed: W5.g: [u0{Cancelling}@dd2f7f4, Dispatchers.Main]
```

**Comment by msasikanth** [comment] 2024-04-18 01:17
That is a really old version of the app, that to an internal build. Have you tested it with the latest release?

**Comment by NoobSam777** [comment] 2024-04-18 01:21
> That is a really old version of the app, that to an internal build.

Yeah, I had downloaded the nightly version to see if the problem had been fixed.


> Have you tested it with the latest release?

Yeah, the same thing happens

**Comment by msasikanth** [comment] 2024-04-18 03:35
Can you screen-record this issue with version 1.39.1 which is the latest production release? I cannot reproduce this issue.

**Comment by msasikanth** [comment] 2024-04-18 03:38
Just to confirm, you had this issue in the production version of the app (latest: 1.39.1) and in the nightly as well?

**Comment by NoobSam777** [comment] 2024-04-19 16:40
> Can you screen-record this issue with version 1.39.1 which is the latest production release? I cannot reproduce this issue.

I cannot record it because it's randomly. It can happen at any time and no crashlog is recorded generally. This is the first crashlog that I get after this happened many times. When the app is open and this happens, the app just closes and does not show any logs

> Just to confirm, you had this issue in the production version of the app (latest: 1.39.1) and in the nightly as well?

Yes

**Comment by msasikanth** [comment] 2024-04-20 01:29
It seems to be a system issue then. I don't see crash reports from anyone else other than your device only on Bugsnag. So, closing this issue since it's not reproducible.

**Closed as not planned by msasikanth** 2024-04-20 01:29 UTC
Labels: bug
