### ISSUE TITLE
Elements change when clicking in one

### ISSUE THREAD

**Issue by MarcCrusellas** [msasikanth/twine#231] opened 2024-01-19 12:17 UTC
**Describe the bug**
The text and image of the code change when cliking in an item

**To Reproduce**
1. Add a third Feed, mine CBS
2. Click in one item big or small
2. See error

**Screenshots**
https://github.com/msasikanth/twine/assets/71900639/e18f3257-7a74-491d-949b-5e615e1a9a38

**Device Information**
 - Device: Samsung Galaxy A23 5G
 - OS: Android 14
 - App Version 1.31.0

**Comment by msasikanth** [comment] 2024-01-19 12:25
I see you are in the unread mode, in this case, if you open a post that post is marked as "read" and removed from the list. So, technically it's working as expected. 

But it looks like it is taking a second or two to open the browser, so the post removal is more noticeable. In settings, you can change the app to open an in-app browser which should be quick. I am also working on reader mode which should make it not noticeable in future updates.

Closing the issue for now, since it's not a bug.

**Closed as completed by msasikanth** 2024-01-19 12:25 UTC
Labels: bug
